### ISSUE TITLE
Voice-Calls broken in 4.4.4_10*

### ISSUE THREAD

**Issue by DrAzraelTod** [VanirAOSP/device_lge_p880#2]
i've tried some of the last builds and voice-calls are broken
4.4.4_091814 works fine
4.4.4_100114 and 4.4.4_100214 i can make calls but the internal mic seems muted (the other side hears nothing, but if i use a bt-headset it works)
4.4.4_100614 network is completely broken and disconnects when i try to make calls

**Comment by nuclearmistake** [comment]
Did data+mic return to functioning by re-flashing the 0918 on the 1001? or did you have to nandroid restore?

If you have time, could you narrow the bug's introduction to one of the builds in between 0918 and 1001?

Having the pair of nightlies where it went from woring in the first to not working in the latter is helpful. Doing a binary search to hone in on which one was the first zip that had issues can reduce the time to do it.

**Comment by DrAzraelTod** [comment]
yeah.. i flashed 4.4.4_091814 and everything was ok again

testing the versions in between might take some time because downloading/flashing/calling takes a bit and i'm probably not getting time to do this before next/second to next weekend.

**Comment by nuclearmistake** [comment]
Take your time... yours is the only report I've seen of an issue with P880, so you might be the only one using p880 or updating it :-P

**Comment by DrAzraelTod** [comment]
yeah.. either that or the issue-list is pretty well hidden :P
